ZVerrouAttendre (->[RAEMACampagnes:20])
OB SET ARRAY:C1227([RAEMACampagnes:20]Arguments:7;"TbF";TbTraducTableauF)
OB SET ARRAY:C1227([RAEMACampagnes:20]Arguments:7;"TbA";TbTraducTableauA)
SAVE RECORD:C53([RAEMACampagnes:20])
ZAmnistiePartielle (->[RAEMACampagnes:20];True:C214)